### ISSUE TITLE
Boot from eMMC

### ISSUE THREAD

**Issue by nikias** [heiher/kernel-nanopi-m4#1]
Hi, have you ever managed to update a kernel for a system that boots from eMMC? I flashed the images to eMMC to the designated locations as per the parameters.txt from the SD eMMC installer image.
```
FIRMWARE_VER: 6.0.1
MACHINE_MODEL: RK3399
MACHINE_ID: 007
MANUFACTURER: RK3399
MAGIC: 0x5041524B
ATAG: 0x00200800
MACHINE: 3399
CHECK_MASK: 0x80
PWR_HLD: 0,0,A,0,1
#KERNEL_IMG: 0x00280000
#FDT_NAME: rk-kernel.dtb
#RECOVER_KEY: 1,1,0,20,0
#in section; per section 512(0x200) bytes
CMDLINE: root=/dev/mmcblk1p7 rw rootfstype=ext4 data=/dev/mmcblk1p8 consoleblank=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 mtdparts=rk29xxnand:0x00002000@0x00002000(uboot),0x00002000@0x00004000(trust),0x00002000@0x00006000(misc),0x00006000@0x00008000(resource),0x00018000@0x0000e000(kernel),0x00010000@0x00026000(boot),0xC84000@0x00030000(rootfs),-@0xCB4000(userdata)
```
I updated the size of the kernel, and moved boot.img to a different location (from 0x4000000 to 0x5000000). I wrote params.img to 8 locations where I found the original ones on eMMC. But it doesn't boot. If I don't update the resources.img the screen turns on and it shows the friendlyELEC boot logo but nothing happens. If I write kernel AND resources image then the screen stays black.
If I write the original kernel image back it boots again.

Do you have any ideas what might be wrong? Anything I could try?

Thanks!

**Comment by nikias** [comment]
Actually tested the same from SD card, also doesn't boot :-(

**Comment by heiher** [comment]
I don't have an eMMC module, so I can't test it.

I have an entire disk image of SD Card. The first partition is the rootfs. You should copy a distro(eg. ArchLinux) to it for test:
1. wget http://hev.cc/sftp/nanopi-m4.img.gz
2. gunzip nanopi-m4.img.gz
3. mkdir rootfs
4. sudo mount -o offset=$((512*196608)) nanopi-m4.img rootfs
5. wget http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz
6. sudo bsdtar -xpf ArchLinuxARM-aarch64-latest.tar.gz -C rootfs
7. sudo umount rootfs
8. sudo dd if=nanopi-m4-img of=/dev/sdX bs=1M # Write nanopi-m4.img to SD Card. WARNING: Output device!!

Good luck!
